config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  resources :notes, only: [:index, :create, :update, :destroy]
  get '*any' => 'notes#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  helper_method :notes, :note
  respond_to :json, only: [:index, :create, :update, :destroy]
  respond_to :html, only: [:index]

  def index
    respond_with notes
  end

  def create
    note = Note.create(note_params)
    respond_with note
  end

  def update
    note.update_attributes(note_params)
    respond_with note
  end

  def destroy
    respond_with note.destroy
  end

  private

  def note_params
    params.permit(:title, :content)
  end

  def notes
    @_notes ||= Note.all
  end

  def note
    @_note ||= notes.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScratchPad</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/notes/show.html.erb
<h1><%= note.title %></h1>
<p><%= note.content %></p>
<%= link_to 'Back', notes_path %>